version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
      - "automated"
    groups:
      github-actions:
        patterns:
          - "*"
      github_actions_security:
        applies-to: security-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/.github/docker-deps"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "automated"
    groups:
      biocontainers:
        patterns:
          - "quay.io/biocontainers/*"
      core-tools:
        patterns:
          - "staphb/*"
          - "broadinstitute/*"
          - "google/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
