#!/usr/bin/env bash
# gen-containers-config.sh: write conf/containers.config, the file Nextflow
# takes every process image from, out of versions.env.
#
# versions.env is the one list of image tags. The bash steps source it; the
# Nextflow modules carry no `container` line and get their image from a
# withName selector in conf/containers.config, which this script writes from
# the PROCESS -> VARIABLE table below. A tag changed in versions.env reaches
# Nextflow when this script runs again, and CI fails until it has.
#
# A plain generated file is used on purpose: config-time Groovy that parses
# versions.env may not survive Nextflow's strict config parser.
#
# Usage:
#   scripts/ci/gen-containers-config.sh              rewrite conf/containers.config
#   scripts/ci/gen-containers-config.sh --check      fail when the committed file is stale,
#                                                    a process has no selector, a selector
#                                                    names no process, or a module sets its
#                                                    own container
#   scripts/ci/gen-containers-config.sh --self-test  prove --check can fail
#   --root DIR                                       work on another tree
set -euo pipefail
export LC_ALL=C   # one sort order for the table, the file and comm

# One row per Nextflow process: its name and the versions.env variable that
# holds its image. A new process needs a row here.
TABLE='
ANCESTRY             PLINK2_IMAGE
ANNOTSV              ANNOTSV_IMAGE
CLINICAL_FILTER      BCFTOOLS_IMAGE
CLINVAR_SCREEN       BCFTOOLS_IMAGE
CNVPYTOR             CNVPYTOR_IMAGE
CNVPYTOR_VCF         BCFTOOLS_IMAGE
CPIC_LOOKUP          PYTHON_IMAGE
CPSR                 PCGR_IMAGE
CYRIUS               PYTHON_IMAGE
DELLY                DELLY_IMAGE
DELLY_BCF2VCF        BCFTOOLS_IMAGE
DUPHOLD              DUPHOLD_IMAGE
DUPHOLD_FILTER       BCFTOOLS_IMAGE
EXPANSION_HUNTER     EXPANSIONHUNTER_IMAGE
HLA_TYPING           T1K_IMAGE
HTML_REPORT          BCFTOOLS_IMAGE
MANTA                MANTA_IMAGE
MITO_EXTRACT_CHRM    BCFTOOLS_IMAGE
MITO_HAPLOGROUP      HAPLOGREP3_IMAGE
MITO_VARIANTS        GATK_IMAGE
MOSDEPTH             MOSDEPTH_IMAGE
MULTIQC              MULTIQC_IMAGE
PHARMCAT             PHARMCAT_IMAGE
PHARMCAT_PREPROCESS  PHARMCAT_IMAGE
PRS                  PLINK2_IMAGE
PYPGX                PYPGX_IMAGE
ROH                  BCFTOOLS_IMAGE
SLIVAR               SLIVAR_IMAGE
SLIVAR_PRIORITIZE    BCFTOOLS_IMAGE
STRANGER             STRANGER_IMAGE
SURVIVOR_MERGE       BCFTOOLS_IMAGE
TELOMERE_HUNTER      TELOMEREHUNTER_IMAGE
VCF_PRECHECK         BCFTOOLS_IMAGE
VCFANNO              VCFANNO_IMAGE
VCFANNO_INDEX        BCFTOOLS_IMAGE
VEP                  VEP_IMAGE
'

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
MODE="write"
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE=check ;;
    --self-test) MODE=self-test ;;
    --root) ROOT=$2; shift ;;
    *) echo "usage: $0 [--check | --self-test] [--root DIR]" >&2; exit 2 ;;
  esac
  shift
done
CONFIG="${ROOT}/conf/containers.config"

# render: print conf/containers.config for the tree in $ROOT. versions.env is
# sourced in a clean shell under `set -u`, so a variable exported by the
# caller cannot stand in for a missing line.
render() {
  local values
  # shellcheck disable=SC2016,SC2046  # $1 and ${!v} expand in the inner shell; the names split on purpose
  values=$(env -i bash --noprofile --norc -c \
    'set -euo pipefail; . "$1"; shift; for v; do printf "%s\t%s\n" "$v" "${!v-}"; done' \
    _ "${ROOT}/versions.env" $(awk 'NF == 2 { print $2 }' <<<"$TABLE" | sort -u))
  printf '%s\n' \
    '// Generated by scripts/ci/gen-containers-config.sh from versions.env. Do not edit:' \
    '// change the tag in versions.env, then run that script again.' \
    'process {'
  awk -F'\t' -v q="'" '
    NR == FNR { val[$1] = $2; next }
    NF == 0 { next }
    {
      split($0, f, /[ \t]+/)
      if (val[f[2]] == "") { printf "ERROR: %s (process %s) is not set in versions.env\n", f[2], f[1] > "/dev/stderr"; bad = 1; next }
      printf "    withName: %s%s%s { container = %s%s%s }\n", q, f[1], q, q, val[f[2]], q
    }
    END { exit bad }
  ' <(printf '%s\n' "$values") <(awk 'NF == 2' <<<"$TABLE" | sort)
  echo '}'
}

# check: print every problem with the tree in $ROOT, exit 1 if there is one.
check() {
  local fail=0 want procs sels p
  want=$(mktemp)
  if ! render > "$want"; then
    fail=1
  elif ! diff -u "$CONFIG" "$want"; then
    echo "FAIL: conf/containers.config does not match versions.env; run scripts/ci/gen-containers-config.sh and commit the result."
    fail=1
  fi
  rm -f "$want"
  procs=$(cat "${ROOT}"/modules/local/*/main.nf | sed -nE 's/^process[[:space:]]+([A-Za-z0-9_]+).*/\1/p' | sort -u)
  [ -n "$procs" ] || { echo "FAIL: found no process in modules/local/*/main.nf"; return 1; }
  sels=$(sed -nE "s/^[[:space:]]*withName:[[:space:]]*'([A-Za-z0-9_]+)'[[:space:]]*\{[[:space:]]*container[[:space:]]*=[[:space:]]*'[^']+'[[:space:]]*\}.*/\1/p" \
    "$CONFIG" 2>/dev/null | sort -u)
  for p in $(comm -23 <(printf '%s\n' "$procs") <(printf '%s\n' "$sels")); do
    echo "FAIL: process ${p} has no container: add a row for it to the table in scripts/ci/gen-containers-config.sh."
    fail=1
  done
  for p in $(comm -13 <(printf '%s\n' "$procs") <(printf '%s\n' "$sels")); do
    echo "FAIL: conf/containers.config has a selector for ${p}, but no process in modules/ has that name."
    fail=1
  done
  if grep -nE '^[[:space:]]*container[[:space:]]' "${ROOT}"/modules/local/*/main.nf; then
    echo "FAIL: the module lines above set their own container; images come from conf/containers.config only."
    fail=1
  fi
  [ "$fail" -eq 0 ] && echo "OK: conf/containers.config matches versions.env and gives all $(wc -l <<<"$procs" | tr -d ' ') processes an image."
  return "$fail"
}

# self_test: plant each kind of fault in a copy of this tree and require
# --check to name it; the unchanged copy must pass.
self_test() {
  local tmp fail=0 rc out
  tmp=$(mktemp -d)
  # shellcheck disable=SC2064
  trap "rm -rf '$tmp'" EXIT
  copy() {
    mkdir -p "${tmp}/$1/conf"
    cp "${ROOT}/versions.env" "${tmp}/$1/"
    cp "${ROOT}/conf/containers.config" "${tmp}/$1/conf/"
    cp -R "${ROOT}/modules" "${tmp}/$1/"
  }
  # expect NAME PATTERN: --check on the planted tree NAME exits 1 and prints PATTERN.
  expect() {
    rc=0; out=$("$0" --check --root "${tmp}/$1" 2>&1) || rc=$?
    if [ "$rc" -ne 1 ] || ! grep -qE -- "$2" <<<"$out"; then
      echo "self-test: '$1' exited ${rc} and did not report /$2/:"; printf '%s\n' "$out"; fail=1
    else
      echo "self-test: '$1' caught: $(grep -E -- "$2" <<<"$out" | head -1)"
    fi
  }

  copy clean
  rc=0; out=$("$0" --check --root "${tmp}/clean" 2>&1) || rc=$?
  [ "$rc" -eq 0 ] || { echo "self-test: the unchanged copy failed:"; printf '%s\n' "$out"; fail=1; }

  # A tag bumped in versions.env without running the generator.
  copy stale
  sed -i.bak -E 's|^(BCFTOOLS_IMAGE="[^"]*:)[^"]*"|\19.99"|' "${tmp}/stale/versions.env"
  expect stale "^\+    withName: 'ROH' \{ container = '[^']*:9\.99' \}"

  # A withName block removed by hand.
  copy no-selector
  sed -i.bak "/withName: 'VEP'/d" "${tmp}/no-selector/conf/containers.config"
  expect no-selector '^FAIL: process VEP has no container'

  # A process added to a module without a table row.
  copy new-process
  printf '%s\n' 'process NEW_TOOL {' '    script:' '    """' '    true' '    """' '}' \
    >> "${tmp}/new-process/modules/local/roh/main.nf"
  expect new-process '^FAIL: process NEW_TOOL has no container'

  # A selector left behind for a process that no longer exists.
  copy stray
  sed -i.bak "s/^process VEP /process VEP_RENAMED /" "${tmp}/stray/modules/local/vep/main.nf"
  expect stray '^FAIL: conf/containers.config has a selector for VEP,'

  # A module that sets its own image again.
  copy literal
  awk -v q="'" '{ print } /^process ROH \{/ { print "    container " q "example/bcftools:1.0" q }' \
    "${ROOT}/modules/local/roh/main.nf" > "${tmp}/literal/modules/local/roh/main.nf"
  expect literal 'main\.nf:[0-9]+: +container .example/bcftools:1\.0.'

  [ "$fail" -eq 0 ] && echo "self-test: OK"
  return "$fail"
}

case "$MODE" in
  write)
    tmp=$(mktemp)
    render > "$tmp"
    cat "$tmp" > "$CONFIG"
    rm -f "$tmp"
    echo "wrote ${CONFIG#"${ROOT}/"}"
    ;;
  check) check ;;
  self-test) self_test ;;
esac
