#!/usr/bin/env bash
# gen-versions-doc.sh — writes docs/versions.md, the table of every container
# image the pipeline pins, from versions.env. The doc pages name the variable
# (for example "${BCFTOOLS_IMAGE}") instead of repeating the tag, so a version
# bump edits versions.env and this generated page, nothing else.
#
# Usage:
#   scripts/ci/gen-versions-doc.sh           rewrite docs/versions.md
#   scripts/ci/gen-versions-doc.sh --check   exit 1 if docs/versions.md is not
#                                            what versions.env produces
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ROOT}/versions.env"
OUT="${ROOT}/docs/versions.md"

render() {
  cat <<'HEADER'
# Image versions

Every container image the pipeline runs, as pinned in [`versions.env`](https://github.com/GeiserX/Personal-Genome-Pipeline/blob/main/versions.env). The step scripts read the variable named here, and the commands on the step pages use the same variable, for example `"${BCFTOOLS_IMAGE}"` after `source versions.env` in the repository root.

This page is generated by `scripts/ci/gen-versions-doc.sh` from `versions.env` and the scripts; edit `versions.env` and rerun the script instead of editing this page. The note column is the comment on that line of `versions.env`. The Nextflow modules take the same tags from `conf/containers.config`, which `scripts/ci/gen-containers-config.sh` writes from `versions.env`; CI fails when that file is stale.

| Group | Tool | Variable | Image | Pinned version | Note |
|---|---|---|---|---|---|
HEADER
  awk '
    function cell(s) { gsub(/\|/, "\\|", s); return s }
    /^# --- .* ---$/ {
      group = $0
      sub(/^# --- /, "", group); sub(/ ---$/, "", group)
      next
    }
    /^[A-Z0-9_]+_IMAGE=/ {
      line = $0
      var = line; sub(/=.*/, "", var)
      note = ""
      if (match(line, /"[[:space:]]+#[[:space:]]*/)) {
        note = substr(line, RSTART + RLENGTH)
        line = substr(line, 1, RSTART)
      }
      val = line; sub(/^[^=]*="/, "", val); sub(/".*$/, "", val)
      # A digest goes first, so a tag+digest pin (python:3.11.17@sha256:...)
      # gives tool python and version 3.11.17@sha256:..., not a tool named
      # after its tag. A tag is a colon after the last slash (a registry port
      # is not one).
      digest = ""
      if (index(val, "@") > 0) {
        digest = substr(val, index(val, "@") + 1)
        val = substr(val, 1, index(val, "@") - 1)
      }
      image = val; tag = ""
      if (match(val, /:[^:\/]*$/)) {
        image = substr(val, 1, RSTART - 1)
        tag = substr(val, RSTART + 1)
      }
      version = (tag != "" && digest != "") ? tag "@" digest : (tag != "" ? tag : (digest != "" ? digest : "(none)"))
      tool = image; sub(/^.*\//, "", tool)
      printf "| %s | %s | `%s` | `%s` | `%s` | %s |\n", cell(group), cell(tool), var, image, version, cell(note)
      n++
    }
    END {
      if (n == 0) { print "gen-versions-doc: no *_IMAGE line found" > "/dev/stderr"; exit 1 }
    }
  ' "$ENV_FILE"

  # Images a script writes out itself instead of reading versions.env
  local hits
  # grep exits 1 when no script hardcodes an image; that is the goal state, not an error
  hits=$(cd "$ROOT" && { grep -oE '(quay\.io/[a-z0-9_-]+|[a-z0-9_-]+)/[a-z0-9_.-]+:v?[0-9][A-Za-z0-9._-]*' scripts/*.sh || true; } \
    | while IFS= read -r line; do
        file="${line%%:*}" ref="${line#*:}"
        grep -qF "\"${ref}\"" "$ENV_FILE" || printf '%s\t%s\n' "$ref" "${file#scripts/}"
      done | LC_ALL=C sort -u)
  if [ -n "$hits" ]; then
    cat <<'LOCAL'

## Images not in versions.env yet

These images are written into the script that uses them, so a change to `versions.env` does not reach them.

| Image | Pinned version | Script |
|---|---|---|
LOCAL
    printf '%s\n' "$hits" | awk -F'\t' '
      { ref = $1; image = ref; sub(/:[^:]*$/, "", image); version = ref; sub(/^.*:/, "", version)
        if (!(ref in files)) { order[++k] = ref; img[ref] = image; ver[ref] = version; files[ref] = $2 }
        else files[ref] = files[ref] ", " $2 }
      END { for (i = 1; i <= k; i++) { r = order[i]; printf "| `%s` | `%s` | %s |\n", img[r], ver[r], files[r] } }'
  fi
}

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$OUT" <(render); then
    echo "docs/versions.md is out of date: run scripts/ci/gen-versions-doc.sh" >&2
    exit 1
  fi
  echo "docs/versions.md matches versions.env"
else
  render > "$OUT"
  echo "wrote ${OUT}"
fi
